import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

const sidebars: SidebarsConfig = {
  docs: [
    'intro',
    {
      type: 'category',
      label: 'Embedded C/C++',
      collapsible: true,
      collapsed: false,
      items: [
        'embedded-cpp/overview',
        'embedded-cpp/bare-metal-c',
        'embedded-cpp/misra-c',
        'embedded-cpp/memory-management',
        'embedded-cpp/volatile-and-registers',
        'embedded-cpp/interrupt-driven-design',
        'embedded-cpp/fixed-point-math',
        'embedded-cpp/deterministic-cpp',
        'embedded-cpp/embedded-toolchains',
        'embedded-cpp/testing-embedded',
      ],
    },
    {
      type: 'category',
      label: 'Real-Time Operating Systems',
      collapsible: true,
      collapsed: false,
      items: [
        'rtos/overview',
        'rtos/freertos',
        'rtos/vxworks',
        'rtos/rtems',
        'rtos/zephyr',
        'rtos/scheduling',
        'rtos/ipc-patterns',
        'rtos/timing-analysis',
        'rtos/watchdog-patterns',
        'rtos/posix-psp',
      ],
    },
    {
      type: 'category',
      label: 'Space Hardware',
      collapsible: true,
      collapsed: false,
      items: [
        'space-hardware/overview',
        'space-hardware/radiation-effects',
        'space-hardware/radiation-hardening',
        'space-hardware/microcontrollers',
        'space-hardware/fpga-in-space',
        'space-hardware/spacecraft-buses',
        'space-hardware/power-systems',
        'space-hardware/thermal-vacuum',
        'space-hardware/cubesat-hardware',
        'space-hardware/sensors-actuators',
      ],
    },
    {
      type: 'category',
      label: 'Flight Software Architecture',
      collapsible: true,
      collapsed: false,
      items: [
        'flight-software/overview',
        'flight-software/cfs-framework',
        'flight-software/command-telemetry',
        'flight-software/state-machines',
        'flight-software/fault-management',
        'flight-software/health-safety',
        'flight-software/data-stores',
        'flight-software/boot-sequence',
        'flight-software/software-updates',
        'flight-software/ground-interface',
      ],
    },
    {
      type: 'category',
      label: 'Orbital Physics',
      collapsible: true,
      collapsed: false,
      items: [
        'orbital-physics/overview',
        'orbital-physics/keplerian-orbits',
        'orbital-physics/orbit-propagation',
        'orbital-physics/coordinate-frames',
        'orbital-physics/attitude-representation',
        'orbital-physics/adcs-software',
        'orbital-physics/kalman-filter',
        'orbital-physics/time-systems',
        'orbital-physics/relativistic-effects',
        'orbital-physics/link-budget',
      ],
    },
    {
      type: 'category',
      label: 'Safety & Reliability',
      collapsible: true,
      collapsed: false,
      items: [
        'safety-reliability/overview',
        'safety-reliability/do-178c',
        'safety-reliability/ecss-standards',
        'safety-reliability/static-analysis',
        'safety-reliability/formal-verification',
        'safety-reliability/redundancy-patterns',
        'safety-reliability/testing-strategy',
        'safety-reliability/fault-injection',
        'safety-reliability/code-review-process',
        'safety-reliability/certification-path',
      ],
    },
    {
      type: 'category',
      label: 'Synthesis',
      collapsible: true,
      collapsed: false,
      items: [
        'synthesis/overview',
        'synthesis/attitude-control-loop',
        'synthesis/safe-mode-fsm',
        'synthesis/ccsds-parser',
        'synthesis/ecc-memory-scrubber',
        'synthesis/watchdog-supervisor',
        'synthesis/tmr-voter',
        'synthesis/orbit-propagator',
        'synthesis/power-budget-manager',
        'synthesis/telemetry-pipeline',
      ],
    },
    {
      type: 'category',
      label: 'Reference',
      collapsible: true,
      collapsed: false,
      items: [
        'reference/latency-numbers',
        'reference/glossary',
        'reference/standards-index',
        'reference/companies',
        'reference/external-resources',
      ],
    },
  ],
};

export default sidebars;
